# Generated by Django 5.2.4 on 2025-07-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historyset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
