# Generated by Django 5.2.4 on 2025-07-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcribeset',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Transcribe',
        ),
        migrations.DeleteModel(
            name='TranscribeSet',
        ),
    ]
