@startuml
entity "User" as user {
  *id : ObjectId <<PK>>
  --
  *username : String <<UNIQUE>>
  *name : String
  *email : String <<UNIQUE>>
  *password : String
  is_staff : Boolean
  is_active : Boolean
  created_at : Date <<AUTO>>
  last_login : Date <<AUTO>>
}

entity "Transcribe" as transcribe {
  *id : String <<PK>>
  --
  *sentence: String
  *transcribe_set_id:  <<FK>>
  created_at: Date <<AUTO>>
}

entity "TranscribeSet" as transcribeSet {
  *id : String <<PK>>
  --
  *title: String
  *user_id: String <<FK>>
  created_at: Date <<AUTO>>
}

transcribe }|--|| transcribeSet : has many
user ||--o{ transcribeSet : has many
@enduml